### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by IUCHIDAISUKE** [IUCHIDAISUKE/42TestChecker#1]
## Object

We haven't good test checker.
So It is checked on an individual basis.
This has pros and cons.

But I'm a lazy person.
It would be very time consuming to type in and check each and every test code, so I automate it so that all the tests are done automatically after I type in the test samples.
It's similar to Moulinette in 42.

## TODO

- [ ] What are the design specifications?
- [ ] connect to the database?
- [ ] need norminette(code checker like pep8(python))?
- [ ] make a new shell?
